# Publish

name: Publish

# Controls when the workflow will run
on:
  # Triggers the workflow on push event, but only for main branch
  push:
    branches:
      - main
  # Triggers the workflow on pull request event, but only for pull request to main branch
  # pull_request is not allowed to use secrets, so we use pull_request_target instead
  pull_request_target:
    branches:
      - main
    types:
      - opened
      - synchronize
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  # default contents: read & write (in forked repos, only read)
  contents: write
  # default deployments: read & write (in forked repos, only read)
  deployments: write
  # default pull-requests: read & write (in forked repos, only read)
  pull-requests: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Deploy
  deploy:
    name: Deploy
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18]
    # Cancel previous runs that are not completed yet
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run generate
        run: npm run generate

      - name: Publish to Cloudflare Pages
        id: cloudflare-pages-deploy
        uses: cloudflare/pages-action@v1
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          projectName: jaoweb
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Create commit comment
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: peter-evans/commit-comment@v2
        with:
          body: |
            ### ⚡ Successfully Cloudflare Pages deployed!
            | Name | Link |
            | :--- | :--- |
            | <span aria-hidden="true">🔨</span> Latest commit | ${{ github.sha }} |
            | <span aria-hidden="true">🔍</span> Latest deploy log | ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} |
            | <span aria-hidden="true">😎</span> Deploy Preview Url | [${{ steps.cloudflare-pages-deploy.outputs.url }}](${{ steps.cloudflare-pages-deploy.outputs.url }}) |
            | <span aria-hidden="true">🌳</span> Environment | ${{ steps.cloudflare-pages-deploy.outputs.environment }} |

      - name: Create PR comment
        if: ${{ github.event_name != 'push' }}
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            ### ⚡ Successfully Cloudflare Pages deployed!
            | Name | Link |
            | :--- | :--- |
            | <span aria-hidden="true">🔨</span> Latest commit | ${{ github.sha }} |
            | <span aria-hidden="true">🔍</span> Latest deploy log | ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} |
            | <span aria-hidden="true">😎</span> Deploy Preview Url | [${{ steps.cloudflare-pages-deploy.outputs.url }}](${{ steps.cloudflare-pages-deploy.outputs.url }}) |
            | <span aria-hidden="true">🌳</span> Environment | ${{ steps.cloudflare-pages-deploy.outputs.environment }} |
